# Generated by Django 5.0.1 on 2024-09-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online', '0002_recruiter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recruiter',
        ),
    ]
