# Generated by Django 5.0.1 on 2024-09-14 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online', '0004_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_data', models.DateField()),
                ('job_title', models.CharField(max_length=255)),
                ('job_salary', models.FloatField(max_length=25)),
                ('image', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('skill', models.CharField(max_length=500)),
                ('created_date', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online.recruiter')),
            ],
        ),
    ]
