# Generated by Django 5.0.1 on 2024-09-14 11:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online', '0005_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
