# Generated by Django 5.0.1 on 2024-09-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online', '0006_alter_jobs_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
