# Generated by Django 5.0.1 on 2024-09-25 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online', '0007_rename_end_data_jobs_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('applydate', models.DateField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online.jobs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online.studentuser')),
            ],
        ),
    ]
